version: 2.1

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

jobs:
  build:
    working_directory: ~/example_application
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@5'
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install_npm
          command: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: dependency-cache-{{ checksum "package-lock.json" }}
      # Skipping the test step since there are no tests
      # - run:
      #     name: Run Tests
      #     command: npm test

  deploy:
    docker:
      - image: circleci/node:10.16.3
    steps:
      - add_ssh_keys:
          fingerprints:
            - "SHA256:rMmcVP/OxXIUubywJjNGu24IteAn652a9K4mI67pqc0"
      - run:
          name: Deploy-Application
          command: ssh -i privatekey.pem -o StrictHostKeyChecking=no ec2-user@ec2-3-249-2-225.eu-west-1.compute.amazonaws.com "rm -rf DevOpsSecCA/;git clone https://github.com/rybarski/DevOpsSecCA.git; source DevOpsSecCA/deploy.sh"

